export {default as Navbar} from './Navbar'
export {default as News} from './News'
export {default as Cryptocurencies} from './Cryptocurencies'
export {default as CryptoDetails} from './CryptoDetails'
export {default as Homepage} from './Homepage'